# Generated by Django 4.2.6 on 2023-10-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_evcharginglocation_station_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcharginglocation',
            name='county_council',
        ),
        migrations.RemoveField(
            model_name='evcharginglocation',
            name='district_council',
        ),
        migrations.RemoveField(
            model_name='evcharginglocation',
            name='local_authority',
        ),
        migrations.RemoveField(
            model_name='evcharginglocation',
            name='postcode',
        ),
    ]
