# Generated by Django 4.2.6 on 2023-10-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_evcharginglocation_county_council_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcharginglocation',
            name='address_info_id',
        ),
    ]
